default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: e-adappter_development

test:
  <<: *default
  database: e-adappter_test

production:
  <<: *default
  database: e-adappter_production
  username: seiyaendo
  password: <%= ENV['E-ADAPPTER_DATABASE_PASSWORD'] %>
